Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Global/Extension/NSObject+.swift
Kurly/Kurly/Presentation/Common/Base/BaseView.swift
Kurly/Kurly/Presentation/Common/Base/BaseViewController.swift

- BaseView, BaseViewController를 만들었습니다. 
- View와 ViewController를 만들때는 UI 대신 Base를 넣어주세요 !
`class ViewController: BaseViewController {
}`
- Resolved: #3

[Setting] #3 - BaseView, BaseViewController를 만들었습니다. 

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionView.swift
Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionViewCell.swift
Kurly/Kurly/Presentation/Common/TabBar/TabBarRect.swift
Kurly/Kurly/Presentation/Common/TabBar/TabBarView.swift
Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift
Kurly/Kurly/Presentation/Common/UIComponents/CustomNavigationBar.swift
Kurly/Kurly/Presentation/Detail/ViewController/DetailViewController.swift

- 하단 보라색 CTA 버튼 구현
- 사용 방법: ViewController 또는 View에서 `private let bottomCTAButton = BottomCTAButton(type: .~)` 해주시면 됩니다!!
type은 enum으로 처리해 둬서 .찍으면 나와요 !!!
layout 잡아주실 떄는 leading과 bottom만 잡아줘도 됩니다 ~~
bottom은 `$0.bottom.equalTo(view.safeAreaLayoutGuide).offset(-11)` 으로 통일해주시면 감사하겠습니다 !!
+ 주문 상세보기 뷰 흰색 버튼도 만들었습니다! .orderDetail 써주세요 !!
| PNG | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/f9e976ef-935b-4587-84d0-664ba172ca7e" width ="250">|
- Resolved: #7

[Feature] #7 - 하단 CTA 버튼을 구현했습니다. 

---

Kurly/Kurly/Global/Extension/String+.swift
Kurly/Kurly/Global/Literals/ImageLiterals.swift
Kurly/Kurly/Presentation/AddCart/Components/Stepper.swift
Kurly/Kurly/Presentation/AddCart/Models/Product.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
Kurly/Kurly/Presentation/AddCart/Views/Stepper.swift
Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift

- 상품을 담는 뷰 UI 구현
- -버튼과 +버튼을 누르면 하단 버튼의 가격 변경
- 공용 컴포넌트 중 BottomCTAButton의 width 값을 변경했습니다. 에전 버전은 width가 안 맞으니 해당 PR 머지 후 다시 pull을 받고 작업해주시면 감사하겠습니당 !!
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/a54e1f2e-c7d5-45dd-9887-6d9a2f724501" width ="250">|
- Resolved: #9

[Feature] #9 - 상품 담기 뷰 UI와 로직을 구현했습니다. 

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/AddCart/Components/Stepper.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift

- 프로젝트 파일 추가
- 김민주바보
- Resolved: #13

[Fix] #13 - 프로젝트 파일을 추가했습니다. 

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
Kurly/Kurly/Presentation/Cart/Views/CartView.swift

-  배송지와 전체 물품의 개수를 보여주는 UI 는 Sticky Header 처럼 동작을 하기 때문에 UIView 로 구현 
- 버튼의 동작은 구현하지 않았습니다. 전체적으로 View 가 완료되면 추가 할 예정입니다!
| PNG | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/45564605/dfb46294-131a-46a6-b72f-218369fe79b7" width ="250">|
- Resolved: #18

[Feature] #18 - CartHeaderView UI 를 구현했습니다.

---

Kurly/Kurly/Presentation/FavoriteFood/View/NotifyAddToastView.swift
Kurly/Kurly/Presentation/FavoriteFood/View/NotifyRemoveToastView.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendHeaderView.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift

- 이미지 변수명이 일치하지 않아 작동되지 않아 오류를 수정했습니다.
- 토스트 뷰 이미지 변경
- 버튼의 색상 ImageLiterals에 있는 내용으로 변경
- makeCornerRound 사용으로 수정
| PNG | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/62370742/ad952008-49eb-446b-9371-44db1bbe041a" width ="250">|
- Resolved: [Fix] 토스트 뷰의 이미지와 버튼 색상을 변경하겠습니다. #25

[Fix] #25 - 이미지 이름 수정, makeCornerRound로 변경했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Models/RecommendModel.swift
Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift

- 모달뷰의 cell에 해당하는 Model을 만들고 데이터를 만들어 cell에 연결했습니다.
- Cell에 해당하는 Model 생성했습니다.
- ModelViewController에서 데이터를 선언한 뒤 cell에 바인딩 했습니다.
- 혹시 Model 폴더는 따로 만들어서 같이 모아놓는 건가요? 혹시 몰라서 일단 제 작업폴더에 넣었습니다.
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/62370742/7b04badf-4a79-4340-87dd-a1e419549810" width ="250">|
- Resolved: [Feature] 연관 상품, 추천 상품 모달 뷰의 모델과 데이터를 연결합니다. #28

[Feature] #28 - 연관 상품, 추천 상품 모달 뷰의 모델과 데이터를 연결했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Application/SceneDelegate.swift
Kurly/Kurly/Global/Extension/Int+.swift
Kurly/Kurly/Global/Extension/UILabel+.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift

- 장바구니 담기 버튼을 누르면 나오는 모달창을 구현했습니다. 
- 다른고객이 함께 본 상품은 추후 넣을 예정입니다!
https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/45d4a34e-7f60-4d7d-b3d6-98b943f73fd6
- Resolved: #12

[Feature] #12 - 장바구니 담기 버튼을 누르면 생성되는 뷰 UI를 구현했습니다. 

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
Kurly/Kurly/Presentation/Cart/Views/CartView.swift

- `CartHeaderView` 구현
- `CartItemCollectionViewCell` 구현
- `CartItemHeaderCollectionReusableView` Header 구현
- 각 Button 의 동작 함수 구현
- StackView 를 활용하다 보니.. UI 가 마음대로 위치하지 않아.. 오래걸렸습니다
- 각 섹션마다 구역을 나누기 위한 구분선은 배경색을 gray 로 변경하여 나타내었습니다
- 위의 구현으로 인해 상단바가 gray 로 되어 있습니다... 
- 여러번 수정하였지만 해결하지 못하여 아시는 분은 알려주시면 감사하겠습니다!
| 상품내역 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/45564605/922b0c84-1b21-423b-8b9b-62a1adece378" width ="250">|
- Resolved: #27

[Feature] #27 - 장바구니 뷰의 첫번째 섹션을 구현했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
Kurly/Kurly/Presentation/Detail/Views/FirstSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Views/FourthSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Views/SecondSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Views/ThridSectionHorizontalCollectionViewCell.swift

- 전체 컬렉션 뷰의 네 번째 섹션 셀 호출
- 셀에 들어가는 요소 레이아웃 잡기
- 텍스트 부분 컬러 변경 익스텐션 사용
- 델리게이트 부분 ViewController로 코드 이동
- 나머지 섹션 빨리 구현하고 플로팅 버튼 구현할게욤,,,
| 네 번째 섹션 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/7e929d1e-86b7-46fa-9f25-4f943a074b48" width ="250">|
- Resolved: #35

[Feature] #35 - 상세보기 뷰 네 번째 섹션 구현하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/Detail/Views/FifthSectionCollectionViewCell.swift

- 다섯 번째 섹션 셀 레이아웃잡기
- 다섯 번째 섹션 셀 전체 컬렉션 뷰에 호출
- 섹션 얼마 안남았습니다.
| 다섯 번째 섹션 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/624994d5-e43f-4f25-9acf-b0bdd3638897" width ="250">|
- Resolved: #39

[Feature]#39 - 상세보기 뷰 다섯 번째 섹션 구현하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/Detail/Views/SixthSectionCollectionViewCell.swift

- 마지막 섹션 셀 레이아웃잡기
- 마지막 섹션 셀 전체 컬렉션 뷰에 호출
- 섹션은 완료하였습니다!!!
- 이제 디테일 잡고 하단 찜하기 버튼 구현과 플로팅 버튼 구현하겠습니다..
| 마지막 섹션 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/bc094fce-f7f6-4f41-8089-29a83baa0eeb" width ="250">|
- Resolved: #41

[Feature] #41 - 상세보기 뷰 여섯 번째 섹션 구현하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Application/SceneDelegate.swift
Kurly/Kurly/Presentation/AfterAddCart/Cells/RelatedCollectionViewCell.swift
Kurly/Kurly/Presentation/AfterAddCart/Model/RelatedModel.swift
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift

- 장바구니에 담으면 나타나는 뷰 UI 구현
- CollectionView로 다른 고객이 함께 본 상품 구현했습니당
- TestVC에 다 연결 해놨습니다. 추후 보연이의 DetailVC와 연결하면 됩니다!!
- 다른 고객이 함께 본 상품 CollectionView 이 부분이 여러 번 사용돼서 하나의 커스텀 컬렉션뷰로 만들어놓고 사용하면 좋을 것 같은데 다들 어떻게 생각하시나요..? 여러분들의 의견을 듣고싶습니다 !
- 저는 UI작업은 끝났고 로직 한 개만 수정하면 서버통신을 제외한 나머지는 다 완성될 것 같습니다 ~~
- 제가 머지 속도를 따라가지 못해서 모든 코드에 리뷰를 달아드리지 못해서 죄송합니당 ㅜㅜㅜ 다음주 중으로 한 번 다 같이 만나거나 디코로 코드 방식이나.. 로직이나... 뭐 기타 등등에 대해 논의해보는 시간을 가지면 좋을 것 같습니다. 이건 제가 따로 공지 드릴게요 !!
| PNG | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/a8765778-1b55-41ea-93f1-7137cb67958a" width ="250">|
- Resolved: #32

[Feature] #34 - 장바구니에 담으면 나타나는 뷰 UI를 구현했습니다. 

---

Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/Detail/Views/DetailView.swift

- 전체 컬렉션 뷰 레이아웃 수정
- 이제서야 viewController에 view가 하나씩 있는 구조를 이해했습니다,,,
| 스크롤 영역 수정 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/402c528d-40b2-4d85-896b-420e3d9b6dd9" width ="250">|
- Resolved: #45

[Fix] #45 - 전체 컬렉션 뷰 레이아웃 수정

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Detail/Components/FloatingButton.swift
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift

- 플로팅 버튼 UI와 위, 아래 액션 구현하였습니다.
- 뷰컨이 슬슬 더러워지는거 같은데 혹시,, 코드리뷰로,, 평가 부탁,, 헤헤,,
- GIF가 조금 버벅거리는데 시뮬에선 스무스하게 잘 됩니둥~
| 플로팅 버튼 올라가기 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/78f759ba-b8fe-4f6d-955f-2135911ffc6f" width ="250">|
| 플로팅 버튼 내려가기 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/0d020c55-eb6c-46a6-aff2-de3a9d86a6d4" width ="250">|
- Resolved: #49

[Feature] #49 - 플로팅 버튼 구현하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
Kurly/Kurly/Presentation/Cart/Views/CartItemFooterCollectionReusableView.swift
Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
Kurly/Kurly/Presentation/Cart/Views/CartView.swift
Kurly/Kurly/Presentation/Cart/Views/SavePointView.swift

- 구매할 아이템을 보여줄 `OrderPriceCollectionViewCell` 구현
- Section 간 간격을 주기위한 `CartItemFooterCollectionReusableView` 구현
- 적립 내용을 보여주는 `SavePointView` 구현
- `CartView` 배경색 변경
- `CartViewController` 에 Header, Footer 추가 
- 모든 UI 가 완성되면 동작 로직을 추가 할 예정입니다.
| 장바구니 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/45564605/4782fc06-0659-40f0-aff9-57b27afcca5a" width ="250">|
- Resolved: #37

[Feature] #37 장바구니 뷰의 두번째 섹션을 구현했습니다.

---

Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift

- 추가된 뷰에 필요한 CTA Button 경우의 수 추가했습니다.
- 형님을 위한 버튼
| 추가 코드 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/ecebeb1d-2f5d-4729-84a3-bae18d4ef9fe" width ="250">|
- Resolved: #55

[Add] #55 - CTA Button 경우의 수 추가

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/CustomAlertViewController.swift
Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
Kurly/Kurly/Presentation/AddCart/Views/AlertBuilder.swift

- 물품의 개수가 1인 상태에서 - 버튼을 누르면 최소 구매수량 알림이 뜨도록 만들었습니다. 
- 물품 개수가 변경되면 가격도 함꼐 바뀝니다. 
- 알림창을 띄울때 title, message, button의 항목들을 입력하여 한번에 알림창으로 만들어주기 위해 Builder 패턴을 사용했습니다. 
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/7a0a96d1-fda2-429c-b9b2-d24804d92082" width ="250">|
- Resolved: #34

[Feature] #34 - 물품 개수 변경에 가격도 함께 바뀌는 로직을 구현했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/CompletedOrder /ViewController/CompletedOrderViewController.swift
Kurly/Kurly/Presentation/CompletedOrder /Views/BenefitsInfoView.swift
Kurly/Kurly/Presentation/CompletedOrder /Views/CompletedOrderView.swift

- 구매 혜택을 보여줄 `BenefitsInfoView` 구현
- CompletedOrderView 구현
- 잘 구현 되었는지 확인 부탁드립니다!
| 구매 완료 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/45564605/d6849f31-082a-413f-b638-905e9c6e3ced" width ="250">|
- Resolved: #54

 [Feature] #54 주문 완료 뷰 ( 중앙 )를 구현했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Global/Protocols/CollectionViewCellRegisterDequeueProtocol.swift
Kurly/Kurly/Global/Protocols/Protocols.swift

- Protocol 파일 추가했습니다
- register 부분 수정할게욜
| Protocol file | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/dbc78627-0fd7-4d04-85fe-786a58235816" width ="250">|
- Resolved: #75

[Setting] #75 - CollectionView Protocol 파일 추가

---

Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Detail/Cells/FifthSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Cells/FirstSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Cells/FourthSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Cells/SecondSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Cells/SixthSectionCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/Cells/ThridSectionHorizontalCollectionViewCell.swift
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift

- 컬렉션뷰 프로토콜 익스텐션을 이용해 리팩토링했습니당!
- 근데 헤더, 푸터는 추가 안해서 또해야함,,
| 수정 코드 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/fb469749-6255-4195-8af8-fafd6bb68b61" width ="250">|
- Resolved: #77

[Fix] #77 - UICollectionView register 리팩토링합니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
Kurly/Kurly/Presentation/Cart/Model/CartModel.swift
Kurly/Kurly/Presentation/Cart/Model/OrderModel.swift
Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
Kurly/Kurly/Presentation/Cart/Views/CartView.swift

- 결제 금액에 대한 `OrderModel` 구현
- `CartModel` dummy 데이터 생성 ( 장바구니 담은 상품 조회 API 의 결과를 토대로 작성 )
- Cell Button 동작을 Delegate 로 구현 ( Model 과 Cell 재사용으로 인한 데이터 불일치 제거 )
- `selectAllItemButton` ( 전체 선택 버튼 ) 동작 추가
- `Stepper` 동작 logic 도 Delegate 로 구현 
- 전체 상품 금액을 계산하기 위한 `calculateSelectedItemPrice` 메서드 구현
- 계산, 동작 로직을 UIVew 파일이 아닌 VC 에 최대한 구현하고자 노력하였습니다.
- 잘 동작하는지 확인 부탁드립니다!
| 장바구니 동작 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/45564605/dfa23fa8-fb4f-4374-8d9d-23dcc0c57b2e" width ="250">|
- Resolved: #68

[Feature] #68 - 상품 결제 금액에 관한 로직을 구현했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Global/Protocols/CollectionHeaderViewRegisterDequeueProtocol.swift

- 컬렉션 뷰 헤더, 푸터 프로토콜 익스텐션 파일 올렸습니당
- ㅋㅋ,, 아직 한발 남음 ㅋㅋ
| 파일 추가 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/789ef283-8056-4e1b-9b3f-40bf395d75eb" width ="250">|
- Resolved: #81

[Setting] #81 - CollectionView Header, Footer Protocol 파일 추가

---

.gitignore
Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Global/Extension/Encodable.swift
Kurly/Kurly/Global/Resources/Info.plist
Kurly/Kurly/Network/Base/APIService.swift
Kurly/Kurly/Network/Base/Base.swift
Kurly/Kurly/Network/Base/BaseResponse.swift
Kurly/Kurly/Network/Base/Config.swift
Kurly/Kurly/Network/Base/Config.xcconfig
Kurly/Kurly/Network/Base/HTTPHeaderField.swift
Kurly/Kurly/Network/Base/HTTPMethod.swift
Kurly/Kurly/Network/Base/NetworkError.swift
Kurly/Kurly/Network/Base/NetworkErrorCode.swift
Kurly/Kurly/Network/Base/NetworkRequest.swift
Kurly/Kurly/Network/DTO/ProductResponse.swift
Kurly/Kurly/Network/Service/KingfisherService.swift
Kurly/Kurly/Network/Service/ProductService.swift
Kurly/Kurly/Network/Service/Service.swift
Kurly/Kurly/Presentation/AddCart/Models/Product.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift

- 네트워크(URLSession) 세팅
- 상품 정보 조회 구현 
- 오래기다리셨습니다..!!!.. 늦게해서 죄송합니다.. 의도치 않게 요즘 많이 바빴네요,,,ㅜㅜㅜ
- 세팅만 후딱 해놓으려다가 그래도 어떻게 쓰는지 코드 있으면 좋을 것 같아서 상품 정보 조회도 구현해놨습니다 !!
- 여러분들이 해야할 것은 DTO와 Service를 만들고 VC에서 해당 메서드를 사용해주시면 됩니다 !!
- 사실 저도 URLSession으로 하는건 처음이라서 나름 공부하고 쓰긴 했지만,, 잘 쓴 코드는 아닐 수도 있습니다 !! 양해부탁드려용..
- DTO: 받을 데이터를 Response(Decodable)로 만든다. 서버로 받은 Json을 넣기 때문에 반드시 서버와 변수명, Type이 일치해야한다.  quicktype으로 JSON 돌려서 data안에 있는 것만 쓰면 됩니다 !
-  Service: 네트워크 통신을 하고 Model로 fetch 한다. (참고: description은 서버에서 내용을 안보내줘서 임의로 String 값을 추가했습니다, salePrice가 String값으로 넘어와서 직접 originPrice에 할인율을 곱해서 세일 가격을 만들어줬습니다.. 그냥 이렇게 하긴 했는데 원래는 서버 선생님들께 요청드려서 Int로 바꾸는게 더 좋긴 해요 ㅋㅋ)
- VC에 넣어줘야 할 메서드: Service를 사용하는 메서드, 여기서 result로 뷰를 바인딩한다. -> getProduct로 메서드 이름이 동일해서 헷갈릴 수 있는데 VC에 있는 메서드와 Service에 있는 메서드는 다른 메서드입니다 !! 이 네이밍은 추후 …

[Setting] #73 - 네트워크 초기 세팅과 상품정보 조회를 구현하였습니다. 

---

Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
Kurly/Kurly/Presentation/Cart/Views/CartItemFooterCollectionReusableView.swift
Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendFooterView.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendHeaderView.swift

- 헤더, 푸터까지 수정했습니다!
- 이제 끝!
| 코드 수정 | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/73578631/471db8be-7534-4d07-8f11-624098cb95ba" width ="250">|
- Resolved: #84

[Fix] #84 - UICollectionView Header, Footer register 리팩토링했습니다.

---

Kurly/Kurly/Presentation/Detail/Cells/ThridSectionHorizontalCollectionViewCell.swift
Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift

- 위대하신 민주님께서 커스텀 컬렉션 뷰를 만들어 주셔서 사용하게 되었습니다.
- 제가 만들었던 컬렉션뷰를 지우고 커스텀 컬렉션 뷰로 대체했습니다.
- <보연>님 코드에서 안쓰는 제 collectionView가 있길래 지웠습니다 ! 확인해주세요 !
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/62370742/28b0716b-0d13-4660-9f99-ff2d21b91f4f" width ="250">|
- Resolved: [Fix] Custom CollectionView를 사용하여 리펙토링 합니다. #79

[Fix] #79 - CustomCollectionView로 수정했습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Network/Base/NetworkRequest.swift
Kurly/Kurly/Network/DTO/ProductResponse.swift
Kurly/Kurly/Network/Service/CartService.swift
Kurly/Kurly/Network/Service/ProductService.swift
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift

- 장바구니 무료 배송 API 연결 
- Product API nullable 표시
- Swagger  Schema 보고 nullable한거는 Response에 옵셔널(*?) 붙여주세요 !!!
- 여기서 Example Value 옆에 있는 Schema 누르면 스키마 나옵니당~~~
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/c5462d91-b6df-4027-a77e-ca1cbac98f1f" width ="250">|
- Resolved: #88

[Feature] #88 - 장바구니 무료 배송 API를 연결하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Network/Base/NetworkRequest.swift
Kurly/Kurly/Network/DTO/CartRequest.swift
Kurly/Kurly/Network/Service/CartService.swift
Kurly/Kurly/Network/Service/ProductService.swift
Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift

- 장바구니 담기 API 연결
- 무료배송 가격 로직 수정
- API Service에 minor한 수정을 했습니다.
- 지금  제 VC 두개가 deinit이 안되는 오류가 있어서 추후 수정하겠습니다. 혹시 돌려볼 때 이점 참고해주세요 !
- Resolved: #93

[Feature] #93 - 장바구니 담기 API를 연결하였습니다.

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Network/DTO/RecommendResponse.swift
Kurly/Kurly/Network/Service/RecommendService.swift
Kurly/Kurly/Network/Service/RelatedFoodService.swift
Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift

- 모댤 뷰에 있는 내용을 서버에 연결하기 위해 했습니다.
- 현재 통신에서 png로 되어있지 않아서 결과가 확인되지 않습니다.
- 전 PR단계에서 파일이 하나 누락되어서 급하게 올리겠습니다.
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/62370742/b29a450b-8607-4668-9d24-090c473ff07e" width ="250">|
- Resolved: #98

[Feature] #98 함께 구매하면 좋은 상품 API를 연결합니다.

---

Kurly/Kurly/Network/Service/RecommendService.swift
Kurly/Kurly/Presentation/AfterAddCart/Model/RelatedModel.swift
Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomCollectionView.swift
Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift

- 함께 구매하면 좋은 상품의 통신이 적용되지 않았습니다.
- CustomCollectionView의 Section마다 bindData를 하도록 했습니다.
| PNG | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/62370742/899eeeb5-0191-4309-a944-528d69aae752" width ="250">|
- Resolved: #103

[Fix] 다른 고객이 본 상품, 함께 구매하면 좋은 상품을 수정하겠습니다. #103

---

Kurly/Kurly.xcodeproj/project.pbxproj
Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift

- 모달뷰와 장바구니 뷰 연결
- 모달뷰에 있는 바로구매 버튼을 누르면 장바구니 뷰로 넘어갑니다.
- 이게 과제 제출 전 마지막 PR이 될 것 같습니당.. 모두들 고생해따 !!!!!
| GIF | <img src = "https://github.com/DO-SOPT-CDS-APP-7/Kurly-iOS/assets/89457040/719bf7f0-8d30-4f4e-bfe2-8478837bb0bb" width ="250">|
- Resolved: #110

[Fix] #110 - 모달 뷰와 장바구니 뷰를 연결하였습니다. 
